apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: imed1/client
        ports:
          - containerPort: 3000
        env:
          - name: API
            value: node-svc
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: LoadBalancer
  selector: 
    app: client
  ports:
    - name: tcp
      protocol: TCP
      port: 5000
      targetPort: 3000