apiVersion: v1
kind:  Service
metadata:
  name: mysql
spec:
 
  selector:
    app: mysql
  clusterIP: None
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-st
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: data
         
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: managed-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
